site_name: Tomography
#repo_url: https://github.com/example/repository/
#copyright:

pages:
  - 'index.md'
  - 'Manuals and Guidelines':
    - 'manuals/conda.md'
    - 'manuals/lunarc.md'
  - 'Events':
    - 'events/quantim_mar2019.md'
    - 'events/quantim_nov2018.md'
  - 'references.md'

# Meta data
#site_description:
#site_author:

theme: readthedocs
#markdown_extensions: [codehilite]

