site_name: Tomography
repo_url: https://github.com/zdemat/tomograms.git
#copyright:

nav:
  - 'index.md'
  - 'Projects':
    - 'projects/xphase.md'
  - 'Manuals and Guidelines':
    - 'doc/conda.md'
    - 'doc/lunarc.md'
  - 'Events':
    - 'events/quantim_mar2019.md'
    - 'events/quantim_nov2018.md'
  - 'references.md'

# Meta data
#site_description:
#site_author:

theme: readthedocs
#markdown_extensions: [codehilite]

