site_name: Tomography
repo_url: https://github.com/zdemat/tomograms
#copyright:

nav:
  - Home: index.md
  - Projects:
    - projects/xphase.md
  - Manuals and Guidelines:
    - doc/conda.md
    - doc/lunarc.md
  - Events:
    - Quantim Mar 2019: events/quantim_mar2019.md
    - Quantim Nov 2018: events/quantim_nov2018.md
  - References: references.md

# Meta data
#site_description:
#site_author:

theme: readthedocs
#markdown_extensions: [codehilite]

