site_name: Tomography
repo_url: https://github.com/tomograms/tomograms-doc
#copyright:

nav:
  - Home: index.md
  - Projects:
    - pyPhase:
        - 'About': projects/pyphase/about.md
        - 'Install Directions': projects/pyphase/install.md
        - 'How to use': projects/pyphase/how_to_use.md
        - 'Loading the data': projects/pyphase/loading.md
        - 'Examples':
          - 'Examples': projects/pyphase/examples.md
          - ' Multidistance CFT phase retrieval': projects/pyphase/example1.md
        - 'Data layout': projects/pyphase/structure.md
        - 'API': projects/pyphase/api.md
  - Manuals and Guidelines:
    - doc/conda.md
    - doc/lunarc.md
  - Events:
    - Quantim Mar 2019: events/Quantim_Mar_2019.md
    - Quantim Nov 2018: events/Quantim_Nov_2018.md
  - References: references.md

# Meta data
#site_description:
#site_author:

theme: readthedocs
#markdown_extensions: [codehilite]

