site_name: Tomography
repo_url: https://github.com/tomograms/tomograms-doc
#copyright:

nav:
  - Home: index.md
  - Projects:
      - pyPhase:
          - About: projects/pyphase/about.md
          - Install Directions: projects/pyphase/install.md
          - How to use: projects/pyphase/how_to_use.md
          - Examples: projects/pyphase/examples.md
          - Data layout: projects/pyphase/Data_Layout.md
          - API: projects/pyphase/api.md
      - Mixed-Scale Dense Networks:
        - MS-DN: projects/Mixed-Scale_Dense_Networks/Mixed-Scale_Dense_Networks.md
        - Generate:
            - Generate_Data: projects/Mixed-Scale_Dense_Networks/Generate_Training_Data/Generate_Simulation_Data.md
            - Step 1: projects/Mixed-Scale_Dense_Networks/Generate_Training_Data/Step_1.md
            - Step 2: projects/Mixed-Scale_Dense_Networks/Generate_Training_Data/Step_2.md
            - Step 3: projects/Mixed-Scale_Dense_Networks/Generate_Training_Data/Step_3.md
        - Train:
            - Train 2D: projects/Mixed-Scale_Dense_Networks/Train_Network/Train_for_2D.md
            - Train 3D: projects/Mixed-Scale_Dense_Networks/Train_Network/Train_for_3D.md
            - Resume/Retrain:  projects/Mixed-Scale_Dense_Networks/Train_Network/Resume_training.md
        - Apply Trained Network: projects/Mixed-Scale_Dense_Networks/Train_Network/Apply_Trained.md
  - Manuals and Guidelines:
    - doc/conda.md
    - doc/lunarc.md
  - Events:
    - Quantim Mar 2019: events/Quantim_Mar_2019.md
    - Quantim Nov 2018: events/Quantim_Nov_2018.md
  - References: references.md

# Meta data
#site_description:
#site_author:

theme: readthedocs
#markdown_extensions: [codehilite]

